### ISSUE TITLE
App directory support

### ISSUE THREAD

**Issue by mcAnastasiou** [honeybadger-io/nextjs-with-honeybadger#14]
A few days ago, nextJS set app directory as stable version. Currently honeybadger is not working properly with this. Will you update it?

**Comment by subzero10** [comment]
Hey @mcAnastasiou, thanks for submitting an issue!

Sure, we can update the package to support this.
In the meantime, can you please provide more information as to what is _not working properly_? This will help us when developing support for this feature.

**Comment by subzero10** [comment]
Link to documentation around the new [app directory](https://nextjs.org/docs/app/building-your-application/routing#the-app-directory).

**Comment by mcAnastasiou** [comment]
> Hey @mcAnastasiou, thanks for submitting an issue!
> 
> Sure, we can update the package to support this. In the meantime, can you please provide more information as to what is _not working properly_? This will help us when developing support for this feature.

Hey @subzero10 , thank you a lot for the response. The things that were not working are the following. 
1. Source maps were not uploading for the app directory
2. Whereas i was able to see some errors on honeybadger for in development mode, i couldn't see them in production mode

**Comment by subzero10** [comment]
@mcAnastasiou I have some updates to share:

> 1. Source maps were not uploading for the app directory

I have an example app setup with the changes from this [PR](https://github.com/honeybadger-io/honeybadger-js/pull/1071) and source maps are successfully uploaded. I will push the example apps in the repository as well for reference, you can follow the progress [here](https://github.com/honeybadger-io/honeybadger-js/issues/1072).

> 2. Whereas i was able to see some errors on honeybadger for in development mode, i couldn't see them in production mode

With my project, I was able to see errors being reported in production mode.
However, with the app router setup, [server errors are reported with very limited context](https://nextjs.org/docs/app/building-your-application/routing/error-handling#handling-server-errors) for now. This is a limitation of the package at the moment and I will attempt to address it [here](https://github.com/honeybadger-io/honeybadger-js/issues/1055).
**Note: If you report them manually to Honeybadger, all the context should be available, with the source maps applied.**

You should be able to try this in your projects pretty soon, as soon as the PR is merged!

**Comment by subzero10** [comment]
Hey @mcAnastasiou, App Router is now supported with [@honeybadger-io/nextjs@5.6.0](https://github.com/honeybadger-io/honeybadger-js/releases/tag/%40honeybadger-io%2Fnextjs%405.6.0)!

**Comment by mcAnastasiou** [comment]
> Hey @mcAnastasiou, App Router is now supported with [@honeybadger-io/nextjs@5.6.0](https://github.com/honeybadger-io/honeybadger-js/releases/tag/%40honeybadger-io%2Fnextjs%405.6.0)!

Great news. Thank you very much. Is it fully supported? I mean the issue with limited context on server errors, is it fixed? I will check it locally and i will close the issue if everything works fine. Are there any changes in the documentation? Is there any example on how to use it with the app directory?

**Comment by subzero10** [comment]
> I mean the issue with limited context on server errors, is it fixed?

Unfortunately, no. This issue is tracked [here](https://github.com/honeybadger-io/honeybadger-js/issues/1055).

> Are there any changes in the documentation?

We haven't updated the documentation to display that App Router is supported, but you should be able to test it out by updating to the latest version of `@honeybadger-io/nextjs` and then executing `npx honeybadger-copy-config-files`.
This will create `error.tsx` and `global-error.tsx` files in the `app` directory.

> Is there any example on how to use it with the app directory?

The example app is not yet on Github, but will be soon :).

**Comment by subzero10** [comment]
[Here's](https://github.com/honeybadger-io/honeybadger-js/tree/master/packages/nextjs/examples/app-router) the example app using App Router!
