### ISSUE TITLE
Server-side source maps

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/nextjs-with-honeybadger#3]
We currently support client-side source maps, but not server-side. Since honeybadger.js is now universal, I'd like to be able to support server-side source maps. Adding this issue here since Next.js is where this feature is most requested.

**Comment by paambaati** [comment]
@joshuap Thanks for creating this issue! Also adding something here, not sure if this will have to be its own issue, but the Vercel folks have deprecated the `@zeit/next-source-maps` package in favor of https://github.com/vercel/next.js/pull/13018. It has also graduated from experimental status to stable — https://nextjs.org/docs/advanced-features/source-maps

I haven't looked at the internals yet, but perhaps using this newer method makes it easier to implement SSR sourcemaps?

**Comment by paambaati** [comment]
There is also some additional insight about how Sentry does it here — https://github.com/vercel/next-plugins/issues/634

**Comment by joshuap** [comment]
@paambaati thanks for the extra info, I'm sure that will be helpful!

**Comment by KonnorRogers** [comment]
honeybadger-io/honeybadger-webpack#4 Addresses this. Since the server and browser code both get passed through webpack, theres no additional configuration needed to send server side sourcemaps as far as I can tell. Perhaps it may have module resolution issues when going from `node -> browser`, but I havent hit any issues yet.

**Comment by paambaati** [comment]
@ParamagicDev Thanks for the PR! Some folks would not be comfortable exposing sourcemaps on production, so I believe there should be a path for those people too.

Perhaps a note in the documentation about a build step that removes sourcemap files after upload to Honeybadger is done?

**Comment by KonnorRogers** [comment]
@paambaati If my understanding is correct about the `hidden-source-map` flag in webpack (which I used here), it will build the sourcemaps, but your `.js` files served to the browser will not contain a reference to the sourcemap and thus will not be inspectable. The sourcemap will only be served for purposes of error tracking, but the end user will not have access. 

If you are truly paranoid about sourcemaps making it to end-users, I have an issue waiting for me on the Honeybadger-webpack repo to remove sourcemaps after upload.

https://github.com/honeybadger-io/honeybadger-js/issues/879

Webpack docs:

https://webpack.js.org/configuration/devtool/

> hidden-source-map  | no reference. Possible choice when using SourceMap only for error reporting purposes.

Feel free to correct me if im wrong or if I didnt address something here!

**Comment by paambaati** [comment]
@ParamagicDev Thanks the additional information. I’ll be testing this tomorrow and I can report back with my findings.

**Comment by joshuap** [comment]
OK, so I did some testing on this, and SSR source maps still didn't work by default (there are a number of issues). I *did* manage to get it to work by hacking some things, though. Here's what I did—this isn't production-ready in my opinion, but I'm hoping it's enough for @ParamagicDev to take a closer look. :)

First of all, we use a different API endpoint for client-side JavaScript errors which enables source map processing. I had to create a honeybadger-js branch to send Node errors there as well:

https://github.com/honeybadger-io/nextjs-with-honeybadger/compare/node-source-maps?expand=1

Next, I noticed that Next.js did seem to be generating server-side source maps, but the "Minified URL" associated with them was different from the local file path in the Node.js stack traces. For example, here's what the raw Node stack traces look like:

```
/Users/josh/Code/honeybadger-io/nextjs-with-honeybadger/.next/server/pages/server/test1.js:135:9:in `someMethodName'
```

But the Minified URL associated with the uploaded source map (generated by Next.js and uploaded with our Webpack plugin) is this:

```
http://localhost:3000/_next/pages/server/test1.js
```

My "fix" for that was to substitute file paths via a `Honeybadger.beforeNotify` handler:

https://github.com/honeybadger-io/nextjs-with-honeybadger/compare/node-source-maps#diff-c85e043f1db00b919581c615d87508f7d4ff2bb8058798ebbe475b4a6e087f26R24

That got it working! I also noticed that the Webpack prefix was different for SSR'd pages vs. client-side. For client-side the prefix is "webpack://_N_E/./", while for SSR it's "webpack:///./" — I have no idea why that is, but conditionally changing Honeybadger's `projectRoot` option corrected it:

https://github.com/honeybadger-io/nextjs-with-honeybadger/compare/node-source-maps#diff-c85e043f1db00b919581c615d87508f7d4ff2bb8058798ebbe475b4a6e087f26R20
https://github.com/honeybadger-io/nextjs-with-honeybadger/compare/node-source-maps#diff-c85e043f1db00b919581c615d87508f7d4ff2bb8058798ebbe475b4a6e087f26R33

With that change, I was able to trigger both client-side AND server-side errors and have source maps applied. Sending the Webpack `projectRoot` allows our GitHub integration to link to the source code on GitHub.

Client-side error:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/474649/112045072-ab4e4f00-8b07-11eb-9a71-b0c501985a0e.png">

Server-side error:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/474649/112045203-d20c8580-8b07-11eb-815d-bbe7a5b94840.png">

My "fix" feels pretty hacky. It would help to understand why Next.js generates the server-side source maps like it does. Do you think there's a way to improve this experience, @ParamagicDev?

**Comment by joshuap** [comment]
I should also mention that client-side and server-side errors are *not* grouped, even if they're technically the same error, since the stack traces are actually quite different.

**Comment by KonnorRogers** [comment]
@joshuap this appears to be a limitation of the Server side vs Client side sourcemaps. Unfortunately most of this is hidden away into Next's implementation. I managed to dig up the Sentry example and heres how they handle the differences:

https://github.com/vercel/next.js/blob/canary/examples/with-sentry/next.config.js

You can luckily differentiate between server and client side maps via `options.isServer` since NextJS does two pass throughs, 1 for Node, 1 for Browser.

I imagine we may have to implement something similar to get sourcemaps working properly.

**Comment by paambaati** [comment]
@joshuap @ParamagicDev Would it be okay to use these changes in production now? I've managed to live quite a while without backend sourcemaps but my app is slowly going complex and I'd absolutely love sourcemaps with my stacktraces.

To summarize the changes —

1. Upgrade `@honeybadger-io/js` package to the `honeybadger-io/honeybadger-js#node-source-maps` version.
2. Upgrade `@honeybadger-io/webpack` package to the `^1.3.0-beta.0` version.
2. Modify the `Honeybadger.beforeNotify` handler like this — [`node-source-maps`#diff-c85e043f1d](https://github.com/honeybadger-io/nextjs-with-honeybadger/compare/node-source-maps#diff-c85e043f1db00b919581c615d87508f7d4ff2bb8058798ebbe475b4a6e087f26R24)

**Comment by joshuap** [comment]
@paambaati sure, go for it. Your summary looks correct. Let me know if you run into any issues. It would be great if you could check back in after using it for a while and let us know what improvements we can make. :)

**Comment by paambaati** [comment]
@joshuap Great then, I'll do that. A quick question — in [`node-source-maps`#diff-c85e043f1d](https://github.com/honeybadger-io/nextjs-with-honeybadger/compare/node-source-maps#diff-c85e043f1db00b919581c615d87508f7d4ff2bb8058798ebbe475b4a6e087f26R17-R20),

you've declared a variable `projectRoot` set to `process.cwd()`, but you haven't used it. Is that intentional, or should `projectRoot` actually be the current working directory instead of `webpack:///./`?

**Comment by paambaati** [comment]
@joshuap Looks like I can't use `honeybadger-io/honeybadger-js#node-source-maps` as a version for `@honeybadger-io/js` because it doesn't include the built output. It might have to be built and then published as a specific version to be able to import it.

**Comment by KonnorRogers** [comment]
@joshuap without additional config options, I think your branch is the most effective way to solve the issue.

I think ideally at some point we'll have to have the Webpack plugin allow the user to strip / replace urls and paths. Unfortunately, this is kind of one of those edge cases that where we're kind of at the mercy of NextJS since its the prefix they chose for their library. 

https://github.com/vercel/next.js/pull/15955

Id have to do some digging around the Webpack docs to see if theres a nicer way to detect prefixes and strip them.

**Comment by joshuap** [comment]
> Id have to do some digging around the Webpack docs to see if theres a nicer way to detect prefixes and strip them.

@ParamagicDev feel free to do some digging if you want to. We can leave this issue open in the meantime.

> Looks like I can't use `honeybadger-io/honeybadger-js#node-source-maps` as a version for `@honeybadger-io/js` because it doesn't include the built output. It might have to be built and then published as a specific version to be able to import it.

@paambaati ah, I'll merge and release that branch, then. Will comment back here when that's done.

**Comment by joshuap** [comment]
[@honeybadger-io/js v3.2.0](https://www.npmjs.com/package/@honeybadger-io/js) has been released with the node-source-maps changes.

**Comment by subzero10** [comment]
This should be fixed with [Honeybadger's official nextjs package](https://www.npmjs.com/package/@honeybadger-io/nextjs).
