### ISSUE TITLE
Server-side exceptions are not recorded when deployed to Vercel

### ISSUE THREAD

**Issue by BethanyBerkowitz** [honeybadger-io/nextjs-with-honeybadger#9]
When I deploy to Vercel, I can't get server-side errors to show up in Honeybadger. All the server pages give me a 404. The Vercel log looks like this: 
<img width="1152" alt="Screen Shot 2022-12-28 at 10 49 57 AM" src="https://user-images.githubusercontent.com/16493493/209842735-7a2ed316-3bb0-4c88-ba06-185a34c6a221.png">
So it appears that the function is getting called and erroring as I'd expect (500) but then displaying a 404. I don't yet understand why the "Edge Status" differs from the "Function Status". 

I did confirm that there's nothing wrong with the routing, by adding another page within the `/server` folder that does not throw an error. That page loads fine on Vercel, so it's definitely related to error handling and not a true 404. 

`_error.js` is getting called, however it's getting called for the 404, not the 500. The `err` object is null. 
<img width="439" alt="Screen Shot 2022-12-29 at 9 55 36 AM" src="https://user-images.githubusercontent.com/16493493/209970842-5dcc0a6f-af84-4f89-b5cd-d88dfca2f7a1.png">

Based on [comments from @subzero10](https://github.com/honeybadger-io/nextjs-with-honeybadger/issues/7#issuecomment-1035518649) I do not think these Vercel issues are new.

**Comment by subzero10** [comment]
Hey @BethanyBerkowitz, I remember not being able to get server errors on Honeybadger, but I'm pretty sure I didn't face this problem. I don't even remember if I was running the example app as an [_Edge Function_](https://vercel.com/docs/concepts/functions/edge-functions); I think it was a standard Serverless function.

Could it be a caching issue, considering that vercel's edge network is all about latency and performance?
What if you try making that route return a _hello world_ message, see that it works and then changing it back to throw an error?

Finally, have you looked into your [function's logs](https://vercel.com/docs/concepts/deployments/logs#function-logs) in Vercel?

**Comment by BethanyBerkowitz** [comment]
> Hey @BethanyBerkowitz, I remember not being able to get server errors on Honeybadger, but I'm pretty sure I didn't face this problem. I don't even remember if I was running the example app as an [_Edge Function_](https://vercel.com/docs/concepts/functions/edge-functions); I think it was a standard Serverless function.
> 
> Could it be a caching issue, considering that vercel's edge network is all about latency and performance? What if you try making that route return a _hello world_ message, see that it works and then changing it back to throw an error?
> 
> Finally, have you looked into your [function's logs](https://vercel.com/docs/concepts/deployments/logs#function-logs) in Vercel?

@subzero10 yes, the screenshot above is from the function's logs. I don't really understand Vercel's functions vs edge functions, and I definitely don't know why the behavior is different on Vercel than locally or on Heroku. I sent a support ticket to Vercel with a very [minimal reproduction of the issue](https://github.com/BethanyBerkowitz/vercel-test), so I'm hoping they will clarify in the next couple days. 

I also did make sure that the routing worked correctly when the function did not error.

**Comment by subzero10** [comment]
We have an [issue](https://github.com/honeybadger-io/honeybadger-js/issues/1055) for the nextjs package that should solve this, so I will close this one.
